# Типы данных

## Int и float


Int - просто целое число. Float - как double в матлабе

In [6]:
q = 3.5

# преобразование числа float в int
q = int(q)
print(type(q), q)

# преобразование числа int в float
q = float(q)
print(type(q), q)

<class 'int'> 3
<class 'float'> 3.0


Математические операторы

In [19]:
q +=2 # <=> q = q + 2
q -=2
q *=2
q /=2

print('q = ', q)
print('возведение в степень q ** 2 =', q ** 2)
print('возведение в степень pow(q, 2) = ', pow(q, 2))
print('целочисленное деление q // 2 =', q // 2)
print('остаток от деления q % 2 =', q % 2)

q =  3.0
возведение в степень q ** 2 = 9.0
возведение в степень pow(q, 2) =  9.0
целочисленное деление q // 2 = 1.0
остаток от деления q % 2 = 1.0


Для других операций используются модули, например, встроенный в питон модуль math

In [2]:
from math import sin, cos, tan, pi
# в этом случае нам доступны только те функции, которые мы взяли из пакета
print(sin(pi / 2))

1.0

In [4]:
from math import *
# * значит, что мы импортируем все функции, которые есть в math

# но сам модуль math мы не импортируем, поэтому в этом случае вылезет ошибка
math.sqrt(64)

NameError: name 'math' is not defined

Предпочтительнее импортировать либо весь модуль, либо только несколько нужных функций, чтобы не было ошибок и переопределение имен функций или переменных:

In [3]:
import math
# если импортируем модуль таким образом, то обращаться к функциям надо так:
math.sqrt(256)

16.0

Переопределение переменных и имен функций 

In [10]:
# если назвать переменную как какую-то функцию, то она перестанет быть функцией
sin = 5
sin(2)
# чтобы это починить, надо заново импортировать эту функцию

TypeError: 'int' object is not callable

In [ ]:

# не следует нзывать переменные именами, которые используются питоном
# они обычно подсвечиваются другим цветом
del 
file
lambda
math 
int


# обычные переменные просто черные или белые
a 
b

In [29]:
# так можно посмотреть все доступные переменные
# так как мы импортировали все, что есть в модуле math, тут куча всяких переменных
%whos
# % перед функцией значит, что она может использоваться только в тетрадках

Variable    Type                          Data/Info
---------------------------------------------------
acos        builtin_function_or_method    <built-in function acos>
acosh       builtin_function_or_method    <built-in function acosh>
asin        builtin_function_or_method    <built-in function asin>
asinh       builtin_function_or_method    <built-in function asinh>
atan        builtin_function_or_method    <built-in function atan>
atan2       builtin_function_or_method    <built-in function atan2>
atanh       builtin_function_or_method    <built-in function atanh>
b           bool                          True
ceil        builtin_function_or_method    <built-in function ceil>
copysign    builtin_function_or_method    <built-in function copysign>
cos         builtin_function_or_method    <built-in function cos>
cosh        builtin_function_or_method    <built-in function cosh>
degrees     builtin_function_or_method    <built-in function degrees>
e           float                  

## String

In [38]:
q = str(q)
print(type(q), q)

# форматирование строк
q = float(q)
print(f'q = {q:.4f}') # 4 знака после запятой 
print(f'q = {int(q):04d}') # добавить 4 нуля перед числом


print("what's up")
print('"frogs"')

<class 'str'> 1.0
q = 1.0000
q = 0001
what's up
"frogs"


In [41]:
s = 'some text'
s = s.upper()
print(s)
print(s.lower())

SOME TEXT
some text


## Boolean

Для булевых переменных все, что не ноль и не None, это True


In [35]:
b = bool(5454)
print(b)

print(bool(0))
print(bool(None))


True
False
False


In [37]:
a = True
b = False

print('а и б: a & b', a & b)
print('а или б: a | b', a | b)
print('исключающее или: a ^ b', a ^ b)

а и б: a & b False
а или б: a | b True
исключающее или: a ^ b True


None - особый тип, обозначающий абсолютное ничто. Обычно используется как дефолтное значение в функциях. Но если None получился как аутпут функции, значит что-то пошло не так

In [31]:
# с None нельзя работать
r = None
r + 2

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

## List

Список это такой тип данных, в котором может храниться что угодно.

In [98]:
l = [1, 3, [1, 1], '???', cos]
print(l)

[1, 3, [1, 1], '???', <built-in function cos>]


In [99]:
l = [1, 2, 3, 4, 5]
# индексирование начинается с 0
print('первый элемент (индекс 0)', l[0])
print('последний элемент', l[-1])

# когда мы хотим взять несколько элементов
# пишем начальный и последний, но последний не включается
print('элементы с 1 по 3', l[0:3])


print('последние 2 элемента', l[-2:])
print('все элементы до предпоследнего', l[:-2])


первый элемент (индекс 0) 1
последний элемент 5
элементы с 1 по 3 [1, 2, 3]
последние 2 элемента [4, 5]
все элементы до предпоследнего [1, 2, 3]


In [ ]:
# по индексу можно изменять элементы
l[0] = 7

In [100]:
print('длина списка', len(l))

# добавлять в список
# при использовании этих методов изменяется уже существующий список
l.append(22) # добавить в конец списка
l.insert(0, 33) # добавить 33 по индексу 0
l.extend([55, 66, 77]) # добавить элементы из указанного списка в конец списка l
print(l)

# с помощью append и insert можно добавлять и другие списки
l.append([88, 99])
print(l)


длина списка 5
[33, 1, 2, 3, 4, 5, 22, 55, 66, 77]
[33, 1, 2, 3, 4, 5, 22, 55, 66, 77, [88, 99]]


У списков есть один прикол, который становится часто причиной ошибок:

In [101]:
# Если мы хотим сохранить список в другой переменной
w = l # так делать нельзя, потому что в этом случае список w просто ссылается на список l
# если мы добавим новый элемент в список l
l.append(220)
# список w тоже изменится, потому что обе переменные по сути ссылаются на один и тот же список
print(w)
# если добавить что-то в список w, список l тоже изменится
w.append(4444)
print(l)

# чтобы этого измежать нужно присваивать переменной значения из списка
ww = l[:] # тут мы берем из l все значения

# или делать копию изначального списка
from copy import deepcopy
www = deepcopy(l)
l.append(110)
print(www)

[33, 1, 2, 3, 4, 5, 22, 55, 66, 77, [88, 99], 220]
[33, 1, 2, 3, 4, 5, 22, 55, 66, 77, [88, 99], 220, 4444]
[33, 1, 2, 3, 4, 5, 22, 55, 66, 77, [88, 99], 220, 4444]


Списки это не матрицы. С ними математические операции работают не так, как хотелось бы:

In [102]:
a = [1, 2, 3]
b = [4, 5, 6]

# список + список = новый список
print(a + b)
# список * int = повторение списка int раз 
print(a * 2)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3]


In [86]:
# другие операции не будут работать
print(a - 3)

TypeError: unsupported operand type(s) for -: 'list' and 'int'

## Tuple

В кортежах может тоже храниться что угодно. Но в отличие от списков кортежи нельзя изменять

In [112]:
t = (2, '3', [2], cos)

In [113]:
# изменять уже существующие элементы нельзя
t[0] = 7

TypeError: 'tuple' object does not support item assignment

In [105]:
# можно из кортежа сделать список и наоборот
print(list(t))
print(tuple(l))

[2, '3', [2], <built-in function cos>]
(33, 1, 2, 3, 4, 5, 22, 55, 66, 77, [88, 99], 220, 4444, 110)


In [106]:
# кортежи можно резать так же как и списки
print(t[0])
print(t[1:3])

2
('3', [2])


In [109]:
# арифметические операции работают так же так в списках
print(t * 2)
print(t + (9, 9))

(2, '3', [2], <built-in function cos>, 2, '3', [2], <built-in function cos>)
(2, '3', [2], <built-in function cos>, 9, 9)


## Dictionary

Словарь - реализация хэш таблицы. Это штука, в которой хранятся значения и ключи, по которым их можно быстро получить

In [2]:
d = {'ключ': 'значение',
      4: 5,
      1: 'cos'}

# поиск значения по ключу
print(d['ключ'])
print(d[1])
print(d[4])

значение
cos
5


In [3]:
d['новый ключ'] = 'новое значение'
d['ключ'] = 'новое значение по старому ключу'
print(d)

{'ключ': 'новое значение по старому ключу', 4: 5, 1: 'cos', 'новый ключ': 'новое значение'}


In [4]:
d.keys()

dict_keys(['ключ', 4, 1, 'новый ключ'])

In [5]:
d.values()

dict_values(['новое значение по старому ключу', 5, 'cos', 'новое значение'])

In [7]:
for key in d:
    print(key)

ключ
4
1
новый ключ


## Numpy array

Сами по себе матрицы в питоне не реализованы. Можно использовать nested lists (это когда список из списков), но математические операции все еще недоступны. Обычно используют пакет numpy для работы с матрицами. 

In [118]:
# импортируем numpy с более коротким именем
import numpy as np

# array можно создать из списка или кортежа
to_array = [[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]]

a = np.array(to_array)
print(a)
print('матрица размера', a.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
матрица размера (3, 3)


In [124]:
b = np.ones((3, 3)) # создаем массив с единицами размера 3,3 

print('сложение\n', a + b)
print('поэлементное умножение матрицы на матрицу и на число\n', a * b * 8)
print('матричное умножение\n', a @ b) 
print('матричное умножение\n', a.dot(b))


сложение
 [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
поэлементное умножение матрицы на матрицу и на число
 [[ 8. 16. 24.]
 [32. 40. 48.]
 [56. 64. 72.]]
матричное умножение
 [[ 6.  6.  6.]
 [15. 15. 15.]
 [24. 24. 24.]]
матричное умножение
 [[ 6.  6.  6.]
 [15. 15. 15.]
 [24. 24. 24.]]


# Циклы

In [125]:
for i in range(5):
    print(i)

0
1
2
3
4


In [132]:
# с единицы до 10 с шагом 3
for i in range(1, 10, 3):
    print(i)

1
4
7


In [131]:
# с 5 до 0 с шагом -1
for i in range(5, 0, -1):
    print(i)

5
4
3
2
1


Можно итерироваться по строкам, элементам списков, кортежей

In [126]:
for i in 'frogs':
    print(i)

f
r
o
g
s


In [127]:
l = [1, 3, 4, 8, 6]
for i in l:
    print(i)

1
3
4
8
6


In [133]:
i = 0
while i < 10:
    print(i)
    i += 5

0
5


# Условия

In [135]:
for i in range(10):
    if i % 2 == 0:
        print('even')
    elif i % 2 != 0:
        print('odd')
    else:
        print('??')

even
odd
even
odd
even
odd
even
odd
even
odd


In [136]:
s = 'some string'
'string' in s

True

In [137]:
for i in [1, 2, 3, None]:
    if i is None:
        print('None detected')

None detected
